import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Acute-InfoSoft",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/acute-infosoft-logo.png", sizes: "32x32", type: "image/png" },
      { url: "/acute-infosoft-logo.png", sizes: "16x16", type: "image/png" },
    ],
    shortcut: "/acute-infosoft-logo.png",
    apple: [{ url: "/acute-infosoft-logo.png", sizes: "180x180", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
